// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MootraWeb;

#nullable disable

namespace MootraWeb.Migrations
{
    [DbContext(typeof(EmotionDbContext))]
    [Migration("20220103230658_Initial commit")]
    partial class Initialcommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MootraWeb.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Emotion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 1, 3, 17, 6, 58, 80, DateTimeKind.Local).AddTicks(555),
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 1, 3, 17, 6, 58, 80, DateTimeKind.Local).AddTicks(588),
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 1, 3, 17, 6, 58, 80, DateTimeKind.Local).AddTicks(591),
                            Name = "Anxious"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 1, 3, 17, 6, 58, 80, DateTimeKind.Local).AddTicks(592),
                            Name = "Angry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
